---
- name: install Python generic tools and Python applications in researchcloud workspace
  hosts: localhost
  gather_facts: true

  roles:
    - python
    - pyenv
    - role: userspace_applications
      vars:
        - list_userspace_applications:
          - "python-poetry"

