---
- name: create robot user 
  hosts: localhost
  gather_facts: true


# when calling this Ansible script, the following variables MUST be set:
#   robotuser_key   - private key for robot user
#
        
  roles:
    - robotuser

