---
- name: install environment for use by "Ton plugin TEST"
  hosts: localhost
  gather_facts: true

  roles:
    - python
    - pyenv
    - role: userspace_applications
      vars:
        - list_userspace_applications:
          - "10-python-poetry"
          - "70-tweets-collector"
          - "999ready"

