---
- name: install environment for use by "Ton plugin TEST"
  hosts: localhost
  gather_facts: true

  tasks:
    - name: test receipt of CO parameter
      debug:
        msg: "{{ TON_TEST }}"

#  roles:
#    - python
#    - pyenv
#    - uwsgi
#    - flask-app
#    - camunda-server
#    - role: userspace_applications
#      vars:
#        - list_userspace_applications:
#          - "10-python-poetry"
#          - "70-tweets-collector"
#          - "999ready"

