---
- name: install package sshfs
  package:
    name: sshfs
    state: present

- name: ensure that local mountpoint exists
  file:
    path: "{{ sshfs_mountpoint }}"
    state: directory
    owner: "{{ robotuser_name }}"

  
- name: mount remote filesystem using credentials of robot user
  become: true
  become_user: "{{ robotuser_name }}"
  mount:
    src: "sshfs#{{ robotuser_name }}@{{ sshfs_server }}:{{ sshfs_sourcepath }}"
    path: "{{ sshfs_mountpoint }}"
    fstype: "fuse"
    opts: "_netdev,user,idmap=user,identityFile=/home/{{ robotuser_name }}/.ssh/rsa_id,allow_other,default_permissions,reconnect,ServerAliveInterval=20,ServerAliveCountMax=5"
    state: mounted



