---

- name: ensure python3-pip is installed
  package:
    name: python3-pip
    state: present

- name: install Python modules in virtual environment
  pip:
    name: pint
    virtualenv: /home/vagrant/myvirtenv
    virtualenv_command: /usr/bin/python3 -m venv
