---

- name: install iselect
  copy:
    src: "iselect.py"
    dest: "/usr/bin/iselect"
    mode: 0755

- name: install file indicated by iselect-file as zone list
  copy:
    src: "{{ irods_iselect-file }}"
    dest: "/etc/irods_zones.json"
    mode: 0744
  when: irods_iselect-file is defined


