---
# make sure the role sshfs_mount has been called prior to this role and in the SAME playbook
#  so that variable sshfs_mountpoint is still available here
  
- name: umount remote filesystem 
  mount:
    path: "{{ sshfs_mountpoint }}"
    state: unmounted




