---
# returns a list of usernames e.g. ["foo","bar"] in variable {{fact_regular_users}}
#
# assumes a Unix-like environment where all users are listed in /etc/passwd
# selects users that meet the following criteria
#   - userid > 999  which excludes system roles
#   - home directory underneath /home
#
# NB: the filter set "to_json|from_json" is needed to transform a dictionary
#     with unicode strings to a dictionary with ascii strings
#     as json_query expects ascii strings

- name: read database /etc/passwd
  getent:
    database: passwd

- name: set fact regular_users
  set_fact:
    fact_regular_users: "{{ getent_passwd|dict2items|to_json|from_json|
      json_query('[?to_number(value[1]) >`999` && starts_with(value[4], `/home/`) ].key') }}"
