---
- name: ensure java runtime is installed
  package:
    name: "default-jre"
    state: present

#- name: install jar tool
#  package: 
#    name: "default-jdk"
#    state: present
    

- name: create camunda target dir
  file:
    dest: "{{ camunda_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

# we install the shared BPM engine
- name: download and unpack camunda full distribution tar.gz
  unarchive:
    src: "{{ camunda_tar_urldir }}/{{ camunda_tar_urlfile }}"
    remote_src: yes
    dest: "{{ camunda_dir }}"

- name: copy camunda bpm engine config to tomcat config
  copy:
    src: "{{ camunda_tomcatdir }}/conf/bpm-platform.xml"
    remote_src: yes
    dest: "{{ catalina_home }}/conf/bpm-platform.xml"
    owner: root
    group: root
    mode: 0644

- name: copy camunda jars to tomcat lib
  copy:
    src: "{{ camunda_dir }}/lib/"
    remote_src: yes
    dest: "{{ catalina_home }}/lib/"
    owner: root
    group: root
    mode: 0644

      
- name: copy camunda webapps to tomcat webapps dir
  copy:
    src: "{{ camunda_tomcatdir }}/webapps/{{ item }}"
    remote_src: yes
    dest: "{{ catalina_home }}/webapps/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "engine-rest"
    - "examples"

# - name: provide applicationContext configuration
#  template:
#    owner: root
#    group: root
#    mode: 0644
#    src: "applicationContext.xml.j2"
#    dest: "{{ camunda_dir }}/applicationContext.xml"

# todo: update war with applicationContext

# - name: add link to Camunda .war in tomcat webapps dir
#  file:
#    src: "{{ camunda_dir }}/{{ camunda_war_urlfile }}"
#    dest: "{{ catalina_home }}/webapps/{{ camunda_context_name }}.war"
#    state: link

# - name: add camunda as a proxy destination in nginx
#  copy:
#    src: "camunda.conf"
#    dest: "/etc/nginx/app-location-conf.d/camunda.conf"
#    owner: root
#    group: root
#    mode: 0644
#  notify: Restart nginx



 
