---

# depends:
#  - matlab iso file must be located on the system
#  - variables need to be customized to specify a valid file installer key and licence.dat content
#
#  further this install assumes a Linux system with desktop GUI  

# the site-specific information is read into variables from a file
# NB: file format should be yaml, suggested variables are:
#     matlab_file_installation_key
#     matlab_license_text
#     matlab_products  (specify here if not all products are to be installed)
#
- name: check if a configuration file exists
  stat:
    path: "{{ matlab_configfile_path }}"
  register: matlab_c 

- name: if config file exists, load its content into Ansible vars
  include_vars:
    file: "{{ matlab_configfile_path }}"
  when: matlab_c.stat.exists

- name: mount Matlab software iso image as /mnt/matlab-iso
  mount:
    path: /mnt/matlab-iso
    src: "{{ matlab_iso_dir }}/{{ matlab_iso_file }}"
    fstype: iso9660
    opts: loop
    state: present

- name: prepare a silent install inputfile
  template:
    owner: root
    group: root
    mode: 0644
    src: "installer_input.txt.j2"
    dest: "/root/installer_input.txt"


- name: prepare the license.dat file
  template:
    owner: root
    group: root
    mode: 0644
    src: "license.dat.j2"
    dest: "/root/license.dat"


- name: create Matlab target dir
  file:
    dest: "{{ matlab_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

# install matlab ....
# run command ./install -inputFile /root/installer_input.txt
# NB: may take 30 min and 20 GB disk space for full product install
#

# - name: install desktop launcher
#   include: desktop.yml


 
