---
# depends: Ubuntu + desktop GUI
#
# Matlab installation requires you to have prepared 2 files:
#  1) target machine must locally have a file with Matlab software ISO image 
#    NB: You should obtain this ISO image from MathWorks Inc.
#
#  2) target machine must locally have a file with configuration information
#    NB: file format should be yaml, suggested variables are:
#     matlab_file_installation_key
#     matlab_license_text
#     matlab_products  (specify here if not all products are to be installed)
#
# As an alternative approach to 2) one could provide the variables as part of an Ansible playbook
#
- name: check if the configuration file exists
  stat:
    path: "{{ matlab_configfile_path }}"
  register: matlab_c 

- name: if config file exists, load its content into Ansible vars
  include_vars:
    file: "{{ matlab_configfile_path }}"
  when: matlab_c.stat.exists

- name: mount Matlab software iso image as /mnt/matlab-iso
  mount:
    path: /mnt/matlab-iso
    src: "{{ matlab_iso_dir }}/{{ matlab_iso_file }}"
    fstype: iso9660
    opts: loop
    state: present

- name: prepare a silent install inputfile
  template:
    owner: root
    group: root
    mode: 0644
    src: "installer_input.txt.j2"
    dest: "/root/matlab_installer_input.txt"


- name: prepare the license.dat file
  template:
    owner: root
    group: root
    mode: 0644
    src: "license.dat.j2"
    dest: "/root/license.dat"


- name: create Matlab target dir
  file:
    dest: "{{ matlab_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

# NB: may take 30 min and 20 GB disk space for full product install
- name: install Matlab products using silent installation. check log in /tmp for progress
  command: /mnt/matlab-iso/install -inputFile /root/matlab_installer_input.txt
  args:
    chdir: /mnt/matlab-iso

- name: unmount Matlab software iso image, no longer needed
  mount:
    path: /mnt/matlab-iso
    src: "{{ matlab_iso_dir }}/{{ matlab_iso_file }}"
    fstype: iso9660
    opts: loop
    state: absent

- name: install desktop launcher
  include: desktop.yml


 
