---
   - name: create default irods_environment.json for new users
     template:
       src: irods_environment.json.j2
       dest: /etc/skel/.irods/irods_environment.json
       owner: root
       group: root
       mode: '0600'
       


