---
- name: Get ownCloud APT GPG key
  apt_key:
    url: https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_20.04/Release.key
    state: presen

- name: Configure ownCloud apt repository
  apt_repository:
    repo: deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_20.04/ /
    state: present
    update_cache: True

- name: clear APT cache then install ownCloud package
  apt: name=owncloud-client update_cache=yes force=yes

